#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd com.ingeint.attachscan.targetplatform
./plugin-builder $DEBUG_MODE ../com.ingeint.attachscan ../com.ingeint.attachscan.test
